# %% Dictionary for System Codes, Commands, and Parameter Range
command_dict = {

    "Reaction Control Subsystem": {
        "Code": "RCS",
        "Commands": {"CMD01":['THRUST_X', range(0,60)],
                     "CMD02":['THRUST_Y', range(0,60)],
                     "CMD03":['THRUST_Z', range(0,60)],
                     "CMD04":['SAFE_MODE', {0, 1}]}
    },
    "Thermal Control Subsystem": {
        "Code": "TCS",
        "Commands": {"CMD01":['HEATER_ON', {0, 1}],
                     "CMD02":['HEATER_OFF', {0, 1}],
                     "CMD03":['VENT_OPEN_RADIATOR', {0, 1}],
                     "CMD04":['TEMP_SETPOINT', range(-30,60)]}
    },
    "Attitude Control Subsystem": {
        "Code": "ACS",
        "Commands": {"CMD01":['ROTATE_X', range(-360,360)],
                     "CMD02":['ROTATE_Y', range(-360,360)],
                     "CMD03":['ROTATE_Z', range(-360,360)],
                     "CMD04":['SAFE_MODE', {0, 1}]}
    },
    "Command & Data Handling": {
        "Code": "CDH",
        "Commands": {"CMD01":['TRANSMIT_HIGH', {0, 1}],
                     "CMD02":['TRANSMIT_LOW', {0, 1}],
                     "CMD03":['RECEIVE_MODE',{0, 1}],
                     "CMD04":['SAFE_MODE', {0,1}]}
    },
    "Telemetry, Tracking, & Command": {
        "Code": "TTC",
        "Commands": {"CMD01":['TRANSMIT_MODE', {0,1}],
                     "CMD02":['RECEIVE_MODE', {0,1}],
                     "CMD03":['TRACKING_MODE', {0,1}],
                     "CMD04":['SAFE_MODE', {0,1}]}
    },
    "Electrical Power Subsystem": {
        "Code": "EPS",
        "Commands": {"CMD01":['BATTERY_CHARGE_MODE', {0,1}],
                     "CMD02":['POWER_ON_MODULE', {0,1,2,3,4}],
                     "CMD03":['POWER_OFF_MODULE', {0,1,2,3,4}],
                     "CMD04":['VOLTAGE_SETPOINT', range(0,120)]}
    },
    "Payload System 1": {
        "Code": "PL1",
        "Commands": {"CMD01":['START_DATA_ACQUISITION', {0,1}],
                     "CMD02":['STOP_DATA_ACQUISITION', {0,1}],
                     "CMD03":['CALIBRATE_SENSOR', {0,1}],
                     "CMD04":['SAFE_MODE', {0,1}]}
    },
    "Payload System 2": {
        "Code": "PL2",
        "Commands": {"CMD01":['START_DATA_ACQUISITION', {0,1}],
                     "CMD02":['STOP_DATA_ACQUISITION', {0,1}],
                     "CMD03":['CALIBRATE_SENSOR', {0,1}],
                     "CMD04":['SAFE_MODE', {0,1}]}
    }
}
# %%
in_cmd = ('ACS:CMD04:1') #input command
code_in = in_cmd[0:3]
command_in = in_cmd[4:9]
parameter_in = in_cmd[10:]
cmd_el = (code_in,command_in,parameter_in) #Command elements list
# The following function was adapted from suggestions generated by ChatGPT prompt:
# "how to match an item in a list with an item in a nested dictionary in python"
def process_command(cmd_el, command_dict):
    code_in, command_in, parameter_in = cmd_el
    parameter_in = int(parameter_in)  # Convert parameter to an integer if needed
    
    # Iterate through subsystems in the dictionary
    for subsystem, details in command_dict.items():
        if details['Code'] == code_in:  # Match system code
            commands = details['Commands']
            if command_in in commands:  # Match command
                description, param_range = commands[command_in]
                
                # Validate the parameter
                if (isinstance(param_range, range) and parameter_in in param_range) or \
                   (isinstance(param_range, set) and parameter_in in param_range):
                    return f"{subsystem} command {description} executed with parameter {parameter_in}"
                else:
                    return f"Invalid parameter '{parameter_in}' for command '{description}' in subsystem '{subsystem}'."
    
    return f"No match found for system code '{code_in}' or command '{command_in}'."
result = process_command(cmd_el, command_dict)
print(result)